name: Test Build

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: ${{ matrix.arch }} build
    # building OpenWRT packages is super slow, so do it on our self-hosted machines
    runs-on: [self-hosted, linux]
    strategy:
      matrix:
        arch:
          - x86_64
          - mvebu-cortexa9-19.07.9 # turris omnia
          - ath79-generic-21.02.3 # https://openwrt.org/toh/hwdata/tp-link/tp-link_eap225-outdoor_v1

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build
        uses: openwrt/gh-action-sdk@v5
        env:
          ARCH: ${{ matrix.arch }}
          FEEDNAME: manysecured
          # | will get replaced with " "
          EXTRA_FEEDS: src-git|node|https://github.com/nxhack/openwrt-node-packages.git


      - name: Store packages
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.arch}}-packages
          path: bin/packages/${{ matrix.arch }}/packages/*.ipk
